config/routes.rb
Rails.application.routes.draw do
  get 'messages/index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "conversations#index"
  resources :conversations do
    resources :messages
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  has_many :participants
  has_many :users, through: :participants
  has_many :messages
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :conversation

  validates :content, presence: true, length: { maximum: 140 }
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :user
  belongs_to :conversation
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :participants
  has_many :conversations, through: :participants
  has_many :messages

  scope :all_except, ->(user) { where.not(user:) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :set_conversation, only: [:show]

  def index
    @conversations = current_user.conversations
  end

  def show
    redirect_to root_path if @conversation.nil?
  end

  private

  def set_conversation
    @conversation = current_user.conversations.find_by(id: params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_conversation

  def index
    @messages = @conversation.messages
  end

  def new
    @message = @conversation.messages.new
  end

  def create
    @message = @conversation.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.html { redirect_to @conversation, notice: 'message created' }
        format.turbo_stream
      end
    else
      flash[:error] = 'message not created'
      render 'new'
    end
  end

  private

  def message_params
    @params = params.require(:message).permit(:content)
    @params[:user] = current_user
    @params
  end

  def set_conversation
    @conversation = current_user.conversations.find(params[:conversation_id])
    redirect_to conversations_path if @conversation.nil?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/conversations/_conversation.html.erb
<div class="conversation">
  <% conversation.users.each do |user| %>
    <%= link_to(user.email, conversation, data: {turbo_frame: "show_conversation"}) if user.id != current_user.id %> 
  <% end %>
</div>

app/views/conversations/index.html.erb
<div class="container">
  <h4>Chats</h4>
  <%= render @conversations %>
  <%= turbo_frame_tag "show_conversation" do %>
    <div>
      <h1>Empty State</h1>
    </div>
  <% end %>
</div>

app/views/conversations/show.html.erb
<%= turbo_frame_tag "show_conversation" do %>
  <div>
    <h1>Conversations#show <%= @conversation.id %></h1>
  </div>
  <%= turbo_frame_tag "conversation_messages", src: conversation_messages_path(@conversation), loading: 'lazy' do %>
    Loading...
  <% end %>
  <%= turbo_frame_tag "new_message", src: new_conversation_message_path(conversation_id: @conversation.id) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chatapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_with(model: @message, remote: true, url: conversation_messages_path) do |f| %>
  <%= f.text_field :content %>
  <%= f.submit "send"%>
<% end %>

app/views/messages/_message.html.erb
<div class="message">
  <p><%= message.content %></p>
  <small><%= message.created_at %></small>
</div>

app/views/messages/create.turbo_stream.erb
<%= turbo_stream.append "conversation_messages" do %>
  <%= render @message %>
<% end %>

app/views/messages/index.html.erb
<%= turbo_frame_tag "conversation_messages" do %>
  <div class="messages">
    <% if @messages.present? %>
      <%= render @messages%>
    <% else %>
      <span>No Messages</span>
    <% end %>
  </div>
<% end %>

app/views/messages/new.html.erb
<%= turbo_frame_tag "new_message" do %>
  <%= render 'form' %>
<% end %>